// src/shared/utils/texts/br.ts
const br = {
  header: {
    menuItem1: 'Que fazemos',
    menuItem2: 'Portfólio',
    menuItem3: 'Sobre nós',
    menuItem4: 'Contato',
    developBy: "Desenvolvido por",
  },
  footer: {
    share: "Compartilhar página",
    centerTitle: "Contacte-nos",
    rightTitle: "Nossa Web",
    allRights: "™ | Desenvolvido por",
  },
  hero: {
    h1: "Criamos sites modernos, lojas virtuais e gerenciamos redes sociais para impulsionar sua marca. Design digital com impacto.",
    title1: "Somos",
    title2: "InPulse",
    title3: "Design",
    subtitle1: "Damos ritmo à sua marca.",
    subtitle2a: "Construímos a presença digital que você precisa.",
    subtitle2b: "Usamos sua essência como inspiração.",
    subtitle2c: "Criamos designs que transmitem confiança.",
    button: "Escreva-nos",
  },
  whatWeDo: {
    title1: "MATERIALIZAMOS TU...",
    subtitle1: "Somos un estudio de diseño digital.",
    product1Title: "Tienda Web",
    product1Subtitle: "Mostrá tus productos online y agilizá tus ventas.",
    product2Title: "Portfolio Virtual",
    product2Subtitle: "Presentá tus trabajos de manera profesional y atractiva.",
    product3Title: "Landing Page",
    product3Subtitle: "Conquistá y convertí tus visitantes en clientes.",
    product4Title: "Web Empresarial",
    product4Subtitle: "Dale presencia digital a tu negocio y mostrá su esencia.",
    title2a: "Identidad de Marca",
    title2b: "Diseño",
    title2c: "Desarrollo web",
    subtitle2: "realizados con Inteligencia Artesanal y calidez humana.",
  },
    clients: {
    title1: "CONFIARON EN NOSOTROS",
    titleProduct1: "Tienda Web",
    subtitleProduct1: "Mostrá tus productos online y agilizá tus ventas.",
    titleProduct2: "Portfolio Virtual",
    subtitleProduct2: "Presentá tus trabajos de manera profesional y atractiva.",
    titleProduct3: "Landing Page",
    subtitleProduct3: "Conquistá y convertí tus visitantes en clientes.",
    titleProduct4: "Web Empresarial",
    subtitleProduct4: "Dale presencia digital a tu negocio y mostrá su esencia.",
    titleProduct5: "Web Empresarial",
    subtitleProduct5: "Dale presencia digital a tu negocio y mostrá su esencia.",
  },
  aboutUs: {
    text1: "Nos inspiramos en la",
    textBold1: "esencia de tu marca",
    text2: "y creamos una web en base a",
    textBold2: "tus necesidades.",
    reason1: "Para aumentar tu audiencia.",
    reason2: "Darte a conocer de manera efectiva y atractiva.",
    reason3: "Y convertir tus visitas en clientes satisfechos y fieles.",
  },
  contact: {
    title: "CHARLEMOS SOBRE TU PROYECTO",
    subtitle: "Hola, soy ULI.",
    formSuccess: "¡Mensaje enviado con exito!",
    formError: "Error al enviar el mensaje",
    formNameLabel: "Nombre y Apellido",
    formEmailLabel: "Correo Electronico",
    formPhoneLabel: "Teléfono",
    formMessageLabel: "Escribí acá lo que nos quieras consultar",
    formSubmit: "Enviar",
    formSubmitting: "Enviando...",
  },
};

export default br;