// src/shared/utils/texts/br.ts
const br = {
  header: {
    menuItem1: 'Que fazemos',
    menuItem2: 'Portfólio',
    menuItem3: 'Sobre nós',
    menuItem4: 'Contato',
    developBy: "Desenvolvido por",
  },
  footer: {
    share: "Compartilhar página",
    centerTitle: "Contacte-nos",
    rightTitle: "Nossa Web",
    allRights: "™ | Desenvolvido por",
  },
  hero: {
    h1: "Criamos sites modernos, lojas virtuais e gerenciamos redes sociais para impulsionar sua marca. Design digital com impacto.",
    title1: "Somos",
    title2: "InPulse",
    title3: "Design",
    subtitle1: "Damos ritmo à sua marca.",
    subtitle2a: "Construímos a presença digital que você precisa.",
    subtitle2b: "Usamos sua essência como inspiração.",
    subtitle2c: "Criamos designs que transmitem confiança.",
    button: "Escreva-nos",
  },
  whatWeDo: {
    title1: "MATERIALIZAMOS O SEU...",
    subtitle1: "Somos um estúdio de design digital.",
    product1Title: "Loja Virtual",
    product1Subtitle: "Mostre seus produtos online e aumente suas vendas.",
    product2Title: "Portfólio Digital",
    product2Subtitle: "Apresente seus trabalhos de forma profissional e atrativa.",
    product3Title: "Landing Page",
    product3Subtitle: "Conquiste e converta seus visitantes em clientes.",
    product4Title: "Site Institucional",
    product4Subtitle: "Dê presença digital ao seu negócio e mostre sua essência.",
    title2a: "Identidade de Marca",
    title2b: "Design",
    title2c: "Desenvolvimento Web",
    subtitle2: "feitos com inteligência artesanal e calor humano.",
  },

  clients: {
    title1: "CONFIARAM EM NÓS",
    titleProduct1: "Loja Virtual",
    subtitleProduct1: "Mostre seus produtos online e aumente suas vendas.",
    titleProduct2: "Portfólio Digital",
    subtitleProduct2: "Apresente seus trabalhos de forma profissional e atrativa.",
    titleProduct3: "Landing Page",
    subtitleProduct3: "Conquiste e converta seus visitantes em clientes.",
    titleProduct4: "Site Institucional",
    subtitleProduct4: "Dê presença digital ao seu negócio e mostre sua essência.",
    titleProduct5: "Site Institucional",
    subtitleProduct5: "Dê presença digital ao seu negócio e mostre sua essência.",
  },

  aboutUs: {
    text1: "Nos inspiramos na",
    textBold1: "essência da sua marca",
    text2: "e criamos um site com base nas",
    textBold2: "suas necessidades.",
    reason1: "Para aumentar sua audiência.",
    reason2: "Para tornar sua marca conhecida de forma eficaz e atrativa.",
    reason3: "E transformar suas visitas em clientes satisfeitos e fiéis.",
  },

  contact: {
    title: "VAMOS CONVERSAR SOBRE SEU PROJETO",
    subtitle: "Olá, sou ULI.",
    formSuccess: "Mensagem enviada com sucesso!",
    formError: "Erro ao enviar a mensagem",
    formNameLabel: "Nome completo",
    formEmailLabel: "E-mail",
    formPhoneLabel: "Telefone",
    formMessageLabel: "Escreva aqui o que você deseja nos consultar",
    formSubmit: "Enviar",
    formSubmitting: "Enviando...",
  },
};

export default br;