// src/shared/utils/texts/en.ts
const en = {
  header: {
    menuItem1: 'What we do',
    menuItem2: 'Portfolio',
    menuItem3: 'About Us',
    menuItem4: 'Contact',
    developBy: "Developed by",
  },
  footer: {
    share: "Share page",
    centerTitle: "Contact us",
    rightTitle: "Our Web",
    allRights: "™ | Developed by",
  },
  hero: {
    h1: "We create modern websites, online stores, and manage social media to boost your brand. Digital design with impact.",
    title1: "We are",
    title2: "InPulse",
    title3: "Design",
    subtitle1: "We give your brand a pulse.",
    subtitle2a: "We build the digital presence you need.",
    subtitle2b: "We take your essence as inspiration.",
    subtitle2c: "We create designs that convey trust.",    
    button: "Write to us",
  },
  whatWeDo: {
    title1: "MATERIALIZAMOS TU...",
    subtitle1: "Somos un estudio de diseño digital.",
    product1Title: "Tienda Web",
    product1Subtitle: "Mostrá tus productos online y agilizá tus ventas.",
    product2Title: "Portfolio Virtual",
    product2Subtitle: "Presentá tus trabajos de manera profesional y atractiva.",
    product3Title: "Landing Page",
    product3Subtitle: "Conquistá y convertí tus visitantes en clientes.",
    product4Title: "Web Empresarial",
    product4Subtitle: "Dale presencia digital a tu negocio y mostrá su esencia.",
    title2a: "Identidad de Marca",
    title2b: "Diseño",
    title2c: "Desarrollo web",
    subtitle2: "realizados con Inteligencia Artesanal y calidez humana.",
  },
    clients: {
    title1: "CONFIARON EN NOSOTROS",
    titleProduct1: "Tienda Web",
    subtitleProduct1: "Mostrá tus productos online y agilizá tus ventas.",
    titleProduct2: "Portfolio Virtual",
    subtitleProduct2: "Presentá tus trabajos de manera profesional y atractiva.",
    titleProduct3: "Landing Page",
    subtitleProduct3: "Conquistá y convertí tus visitantes en clientes.",
    titleProduct4: "Web Empresarial",
    subtitleProduct4: "Dale presencia digital a tu negocio y mostrá su esencia.",
    titleProduct5: "Web Empresarial",
    subtitleProduct5: "Dale presencia digital a tu negocio y mostrá su esencia.",
  },
  aboutUs: {
    text1: "Nos inspiramos en la",
    textBold1: "esencia de tu marca",
    text2: "y creamos una web en base a",
    textBold2: "tus necesidades.",
    reason1: "Para aumentar tu audiencia.",
    reason2: "Darte a conocer de manera efectiva y atractiva.",
    reason3: "Y convertir tus visitas en clientes satisfechos y fieles.",
  },
  contact: {
    title: "CHARLEMOS SOBRE TU PROYECTO",
    subtitle: "Hola, soy ULI.",
    formSuccess: "¡Mensaje enviado con exito!",
    formError: "Error al enviar el mensaje",
    formNameLabel: "Nombre y Apellido",
    formEmailLabel: "Correo Electronico",
    formPhoneLabel: "Teléfono",
    formMessageLabel: "Escribí acá lo que nos quieras consultar",
    formSubmit: "Enviar",
    formSubmitting: "Enviando...",
  },
};

export default en;