// src/shared/utils/texts/en.ts
const en = {
  header: {
    menuItem1: 'What we do',
    menuItem2: 'Portfolio',
    menuItem3: 'About Us',
    menuItem4: 'Contact',
    developBy: "Developed by",
  },
  footer: {
    share: "Share page",
    centerTitle: "Contact us",
    rightTitle: "Our Web",
    allRights: "™ | Developed by",
  },
  hero: {
    h1: "We create modern websites, online stores, and manage social media to boost your brand. Digital design with impact.",
    title1: "We are",
    title2: "InPulse",
    title3: "Design",
    subtitle1: "We give your brand a pulse.",
    subtitle2a: "We build the digital presence you need.",
    subtitle2b: "We take your essence as inspiration.",
    subtitle2c: "We create designs that convey trust.",    
    button: "Write to us",
  },
  whatWeDo: {
    title1: "WE BRING YOUR...",
    subtitle1: "We are a digital design studio.",
    product1Title: "Online Store",
    product1Subtitle: "Showcase your products online and boost your sales.",
    product2Title: "Portfolio Website",
    product2Subtitle: "Present your work in a professional and attractive way.",
    product3Title: "Landing Page",
    product3Subtitle: "Engage and convert your visitors into clients.",
    product4Title: "Business Website",
    product4Subtitle: "Give your business a digital presence and showcase its essence.",
    title2a: "Brand Identity",
    title2b: "Design",
    title2c: "Web Development",
    subtitle2: "crafted with artisanal intelligence and human warmth.",
  },

  clients: {
    title1: "TRUSTED BY OUR CLIENTS",
    titleProduct1: "Online Store",
    subtitleProduct1: "Showcase your products online and boost your sales.",
    titleProduct2: "Portfolio Website",
    subtitleProduct2: "Present your work in a professional and attractive way.",
    titleProduct3: "Landing Page",
    subtitleProduct3: "Engage and convert your visitors into clients.",
    titleProduct4: "Business Website",
    subtitleProduct4: "Give your business a digital presence and showcase its essence.",
    titleProduct5: "Business Website",
    subtitleProduct5: "Give your business a digital presence and showcase its essence.",
  },

  aboutUs: {
    text1: "We are inspired by the",
    textBold1: "essence of your brand",
    text2: "and create a website based on",
    textBold2: "your needs.",
    reason1: "To grow your audience.",
    reason2: "To make your brand known in an effective and attractive way.",
    reason3: "And to turn your visitors into loyal and satisfied clients.",
  },

  contact: {
    title: "LET'S TALK ABOUT YOUR PROJECT",
    subtitle: "Hi, I'm ULI.",
    formSuccess: "Message sent successfully!",
    formError: "Error sending the message",
    formNameLabel: "Full Name",
    formEmailLabel: "Email",
    formPhoneLabel: "Phone",
    formMessageLabel: "Write here what you'd like to ask us",
    formSubmit: "Send",
    formSubmitting: "Sending...",
  },
};

export default en;