// src/shared/utils/texts/es.ts
const es = {
  header: {
    menuItem1: 'Qué hacemos',
    menuItem2: 'Portfolio',
    menuItem3: 'Nosotros',
    menuItem4: 'Contacto',
    developBy: "Desarrollado por",
  },
  footer: {
    share: "Compartir página",
    centerTitle: "Contáctanos",
    rightTitle: "Nuestra Web",
    allRights: "™ | Realizado por",
  },
  hero: {
    h1: "Creamos páginas web modernas, tiendas online y gestionamos redes sociales para potenciar tu marca. Diseño digital con impacto.",
    title1: "Somos",
    title2: "InPulse",
    title3: "Design",
    subtitle1: "Le damos pulso a tu marca.",
    subtitle2a: "Construimos la presencia digital que necesitás.",
    subtitle2b: "Tomamos tu esencia como inspiración.",
    subtitle2c: "Creamos diseños que transmiten confianza.",
    button: "Escribinos",
  },
  whatWeDo: {
    title1: "MATERIALIZAMOS TU...",
    subtitle1: "Somos un estudio de diseño digital.",
    product1Title: "Tienda Web",
    product1Subtitle: "Mostrá tus productos online y agilizá tus ventas.",
    product2Title: "Portfolio Virtual",
    product2Subtitle: "Presentá tus trabajos de manera profesional y atractiva.",
    product3Title: "Landing Page",
    product3Subtitle: "Conquistá y convertí tus visitantes en clientes.",
    product4Title: "Web Empresarial",
    product4Subtitle: "Dale presencia digital a tu negocio y mostrá su esencia.",
    title2a: "Identidad de Marca",
    title2b: "Diseño",
    title2c: "Desarrollo web",
    subtitle2: "realizados con Inteligencia Artesanal y calidez humana.",
  },
  clients: {
    title1: "CONFIARON EN NOSOTROS",
    titleProduct1: "Tienda Web",
    subtitleProduct1: "Mostrá tus productos online y agilizá tus ventas.",
    titleProduct2: "Portfolio Virtual",
    subtitleProduct2: "Presentá tus trabajos de manera profesional y atractiva.",
    titleProduct3: "Landing Page",
    subtitleProduct3: "Conquistá y convertí tus visitantes en clientes.",
    titleProduct4: "Web Empresarial",
    subtitleProduct4: "Dale presencia digital a tu negocio y mostrá su esencia.",
    titleProduct5: "Web Empresarial",
    subtitleProduct5: "Dale presencia digital a tu negocio y mostrá su esencia.",
  },
  aboutUs: {
    text1: "Nos inspiramos en la",
    textBold1: "esencia de tu marca",
    text2: "y creamos una web en base a",
    textBold2: "tus necesidades.",
    reason1: "Para aumentar tu audiencia.",
    reason2: "Darte a conocer de manera efectiva y atractiva.",
    reason3: "Y convertir tus visitas en clientes satisfechos y fieles.",
  },
  contact: {
    title: "CHARLEMOS SOBRE TU PROYECTO",
    subtitle: "Hola, soy ULI.",
    formSuccess: "¡Mensaje enviado con exito!",
    formError: "Error al enviar el mensaje",
    formNameLabel: "Nombre y Apellido",
    formEmailLabel: "Correo Electronico",
    formPhoneLabel: "Teléfono",
    formMessageLabel: "Escribí acá lo que nos quieras consultar",
    formSubmit: "Enviar",
    formSubmitting: "Enviando...",
  },
};

export default es;